### ISSUE TITLE
Unable to install and Run Gui on my Linux 

### ISSUE THREAD

**Issue by UddeshyaPandey** [Bonidia/MathFeature#1]
I have been trying to install and run MathFeatures on **Ubuntu**, following **conda install option 4**, as mentioned in GitHub.
 In step 1, the command.
``
$ apt-get install libgtk-3-dev
``
 should install **libgtk-3** but it fails everytime, with connection error
![image](https://user-images.githubusercontent.com/77080877/151710497-69f006bc-ab4c-4f08-aac8-3aaa7a30d4b6.png)

I am using wsl to use ubuntu on my windows 11

If possible, please introduce a method to use math features using the windows command line.

**Comment by Bonidia** [comment]
Dear Uddeshya Pandey,

We hope this email finds you well!

**To work on the Windows command line, you can use these options:**

1 - Installing dependencies and package - Docker Image - Terminal - MathFeature v1.0

To use docker in Windows, see: https://docs.docker.com/desktop/windows/install/

**For Linux command line:**

2 - Installing dependencies and package - Conda - Terminal - Option 3

**Also, we now have a WebServer version of MathFeature available (Linux - Ubuntu, Debian, among others), see:**

3 - https://github.com/Bonidia/MathFeature-WebServer

Please feel free to reach out if you need anything.

Best regards,

Robson P Bonidia.
