### ISSUE TITLE
Download Error in Webserver!

### ISSUE THREAD

**Issue by UddeshyaPandey** [Bonidia/MathFeature#2]
I have been using the math feature web server, but it shows the same download error for a few days.
It is taking inputs and processing it 
![image](https://user-images.githubusercontent.com/77080877/153699755-9544c9b2-997e-42d2-8dc8-20542c7ef0bd.png)

once I press download dataset, this error appears:
![image](https://user-images.githubusercontent.com/77080877/153699709-5ed0fb4b-1be4-4c40-9ad9-c69a7528dae0.png)

Please rectify

PS:
all fields were filled
input files have no issues
it worked before for the same files, and downloads were made smoothly

**Comment by Bonidia** [comment]
Dear Uddeshya Pandey,

We hope this email finds you well!

Are you using the version available at http://mathfeature.icmc.usp.br/? 

If so, we were experiencing server instability, but I think the queue is working normally now. Please try to check!

But if it's the WebServer version for localhost: https://github.com/Bonidia/MathFeature-WebServer, then all the files are in the tmp directory!

Please feel free to reach out if you need anything.

Best regards,

Robson P Bonidia.
