### ISSUE TITLE
errors on chaos game and conventinal methods in webserver

### ISSUE THREAD

**Issue by UddeshyaPandey** [Bonidia/MathFeature#3]
I am encountering a download error while trying conventional methods on the webserver.
Also, the chaos game methods in the mathematical methods section are not working.

**Comment by Bonidia** [comment]
Dear Uddeshya Pandey,

We hope this email finds you well!

Are you using the version available at http://mathfeature.icmc.usp.br/?

If so, we were experiencing server instability. Lots of submissions. Please try checking again! 

If possible, try to install the same version of WebServer on your computer: https://github.com/Bonidia/MathFeature-WebServer

Please feel free to reach out if you need anything.

Best regards,

Robson P Bonidia.
