### ISSUE TITLE
Convert the project into a package and upload to PyPi

### ISSUE THREAD

**Issue by vitorfrois** [Bonidia/MathFeature#5]
It would be much useful to have such tool as a Python package for ML pipeline than as GUI/CLI

**Comment by Bonidia** [comment]
Hello, Vitor! How are you?

Thank you so much for your message!

This is the next phase, and we are trying to find students interested in joining this journey. If you'd like to participate, it would be a pleasure.

Best regards,

**Comment by Bonidia** [comment]
Closed.
